<?php
return array (
	'text'=>"
		<xml>
			<ToUserName><![CDATA[%s]]></ToUserName>
			<FromUserName><![CDATA[%s]]></FromUserName>
			<CreateTime>%s</CreateTime>
			<MsgType><![CDATA[text]]></MsgType>
			<Content><![CDATA[%s]]></Content>
		</xml>
	",
	'music'=>"
	 	<xml>
 			<ToUserName><![CDATA[%s]]></ToUserName>
 			<FromUserName><![CDATA[%s]]></FromUserName>
 			<CreateTime>%s</CreateTime>
 			<MsgType><![CDATA[%s]]></MsgType>
 		<Music>
 			<Title><![CDATA[%s]]></Title>
 			<Description><![CDATA[%s]]></Description>
 			<MusicUrl><![CDATA[%s]]></MusicUrl>
 			<HQMusicUrl><![CDATA[%s]]></HQMusicUrl>
 		</Music>
 		<FuncFlag>0</FuncFlag>
 		</xml>",
 	'news'=>array(
 		'header'=>"
 		<xml>
 		<ToUserName><![CDATA[%s]]></ToUserName>
 		<FromUserName><![CDATA[%s]]></FromUserName>
 		<CreateTime>%s</CreateTime>
 		<MsgType><![CDATA[news]]></MsgType>
 		<ArticleCount>%s</ArticleCount>
 		<Articles>",
 		'body'=>"
 		 <item>
 		 <Title><![CDATA[%s]]></Title>
 		 <Description><![CDATA[%s]]></Description>
 		 <PicUrl><![CDATA[%s]]></PicUrl>
 		 <Url><![CDATA[%s]]></Url>
 		 </item>",
 		 'bottom'=>"
 		 </Articles>
 		 <FuncFlag>1</FuncFlag>
		  </xml> "
		 ),
	'CustomerMsg'=>"
		<xml>
			<ToUserName><![CDATA[%s]]></ToUserName>
			<FromUserName><![CDATA[%s]]></FromUserName>
			<CreateTime>%s</CreateTime>
			<MsgType><![CDATA[transfer_customer_service]]></MsgType>
		</xml>",
	'customsExt'=>"
		<GW_CUSTOMS>
			<CUSTOMS_TYPE><![CDATA[%s]]></CUSTOMS_TYPE>
			<BIZ_TYPE_CODE><![CDATA[%s]]></BIZ_TYPE_CODE>
			<ESHOP_ENT_CODE><![CDATA[%s]]></ESHOP_ENT_CODE>
			<ESHOP_ENT_NAME><![CDATA[%s]]></ESHOP_ENT_NAME>
			<GOODS_FEE><![CDATA[%s]]></GOODS_FEE>
			<TAX_FEE><![CDATA[%s]]></TAX_FEE>
		</GW_CUSTOMS>",
	'MessageHead'=>"<MessageHead><MessageCode>VNB3PARTY_PAYVOUCHER</MessageCode><MessageID>%s</MessageID><SenderID>YXTS</SenderID><SendTime>%s</SendTime><Sign>%s</Sign></MessageHead>",
	'MessageHeadvr'=>"<MessageHead><MessageCode>VNB3PARTY_PAYVOUCHER</MessageCode><MessageID>%s</MessageID><SenderID>YXTS</SenderID><SendTime>%s</SendTime><Sign></Sign></MessageHead>",
	'MessageBody'=>"<MessageBody><customICP>%s</customICP><orderNo>%s</orderNo><payTransactionNo>%s</payTransactionNo><payChnlID>%s</payChnlID><payTime>%s</payTime><payGoodsAmount>%s</payGoodsAmount><payTaxAmount>%s</payTaxAmount><freight>%s</freight><payCurrency>%s</payCurrency><payerName>%s</payerName><payerDocumentType>%s</payerDocumentType><payerDocumentNumber>%s</payerDocumentNumber></MessageBody>",
	'VnbMessage'=>"<VnbMessage>%s<MessageBodyList>%s%s</MessageBodyList></VnbMessage>",
);
